### ISSUE TITLE
httpInspector

### ISSUE THREAD

**Issue by Buksa** [Wain-PC/movian-ingfilm#1]
https://github.com/Wain-PC/movian-ingfilm/blob/master/ingfilm.js#L28
не совсем хорошо так как будет везде енти сувать куки 
просто помну когда я в HDSerials поменял UA глабольно андома в блеклист его занес так как 
конфликтил :)

да глянь последний YouTube 
https://github.com/andoma/movian-plugin-youtube
и 
https://github.com/facanferff/movian-plugin-ign
оно под апи 2 и разбивка на модули

**Comment by Wain-PC** [comment]
Спасибо! Мне показалось, что эта штука должна работать инкапсулированно, в пределах плагина, а не глобально. Модульность посмотрел, прикольно, но в этом плагине смысла особо нет, он небольшой получается. Если только разрастется, тогда разнесу код по модулям.
