### ISSUE TITLE
locateMainPlayerLink

### ISSUE THREAD

**Issue by Buksa** [Wain-PC/movian-ingfilm#2]
https://github.com/Wain-PC/movian-ingfilm/blob/master/ingfilm.js#L237
кажись они чето поменяли сейчас там 
`<div id="player" style="width: 100%; height: 100%;"><iframe src="http://moonwalk.cc/video/fba20112418fe2fc/iframe" width="100%" height="100%" frameborder="0" scrolling="no" allowfullscreen="true"></iframe></div>`

**Comment by Wain-PC** [comment]
Не совсем понял проблему. Только что проверил плагин - вроде бы все работает (кино, сериалы).
Можешь подробнее описать, пожалуйста?

**Comment by Buksa** [comment]
хм может гео 
выбераю "я зомби" 
https://github.com/Wain-PC/movian-ingfilm/blob/master/ingfilm.js#L582
log тут
http://pastebin.com/Qw3eRvA3
дальше 
https://github.com/Wain-PC/movian-ingfilm/blob/master/ingfilm.js#L221
http://pastebin.com/nReDRXEB
все нормално а вот дальше труба
у меня iframe получается другой
https://github.com/Wain-PC/movian-ingfilm/blob/master/ingfilm.js#L236
http://pastebin.com/5RPeNdqa

болшой лог
http://pastebin.com/iwRrfMKy

**Comment by Wain-PC** [comment]
Все-таки не смог воспроизвести, как ни пытался. Вероятно, действительно может быть связано с местоположением. На примере сериала "Я - зомби" у меня получается вот такой iframe:
[http://pastebin.com/4ZzXHeXE](url)

UPD.: Cейчас получилось руками пройти по URL из логов и действительно получить другой формат. Ошибка заключается в параметре style в URL айфрейма. В корректной ссылке он имеет значение 1, в твоей - 4. Откуда там оно взялось, сказать трудно.

**Comment by Wain-PC** [comment]
Исправление выкатил в репозиторий, Beta Pass все тот же. Надеюсь, это должно помочь, но сам проверить не могу - у меня все корректно работает.

**Comment by Buksa** [comment]
угу все терь красива :) 
Молодца
