### ISSUE TITLE
(cannot read property 'voices' of null - - >ingfilm.js:597

### ISSUE THREAD

**Issue by Buksa** [Wain-PC/movian-ingfilm#3]
добавь рефала в запрос 
также андома сменил регехр движок скорей всего нужно будет проверить регексы так как 
при открытии Opening ingfilm:play:hls%3Ahttp%3A%2F%2Fingfilm.ru%2Fvideo
regexec: backtrack overflow!
да и moonwalk сменили авторизацию 
ну и https://movian.tv/news/64

**Comment by Wain-PC** [comment]
Сорри что так долго делал. Ничего страшного, просто ввели новые ограничения по безопасности: теперь требуют наличие валидного заголовка Referer.
Регулярки вроде как нормально работают.
За ссылку на чат спасибо, присоединился!

**Comment by Buksa** [comment]
спасибо молодца насчет regexec: backtrack overflow! вылез при смене движка регехп если uri  длинный то беда
